### ISSUE TITLE
title field missing from backup api

### ISSUE THREAD

**Issue by danmarsden** [clickviewapp/moodle-mod_clickview#5]
https://github.com/clickviewapp/moodle-mod_clickview/blob/main/backup/moodle2/backup_clickview_stepslib.php#L41

https://github.com/clickviewapp/moodle-mod_clickview/blob/main/db/install.xml#L18

not sure if that was accidental/intentional?

**Comment by adpe** [comment]
Thanks @danmarsden 

Will be fixed with https://github.com/clickviewapp/moodle-mod_clickview/commit/e1f989a203e40aa1213ccb46424e784fce584ab7

Cheers, Adrian
